export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <header
        className="bg-blue-300 p-2"
        >Navbar</header>
        {children}
        <footer  className="bg-slate-300 p-2">Footer</footer>
      </body>
    </html>
  )
}
